apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-dep
spec:
  
  replicas: 2
  selector:
    matchLabels:
      env: prod
   template:
    metadata:
      name: "webpod4"
      labels:
        env: prod
  

    spec:
      containers:
      - name: "webc1"
        image: dockerhandson/java-web-app:2
        ports:
          - containerPort: 8080
          
