name: CICD
on:
  push:
    branches: [ master ]

jobs:
  job1:
    runs-on: self-hosted
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: deploy to k8s
       run: |
          kubectl apply -f deplyment.yml
          kubectl apply -f service.yml
          

 
